In [ ]:
import numpy as np
x=np.array([1,2,3,4])      #array of list
print(x,type(x))
x
print(x.ndim)               #no of dimension


[1 2 3 4] <class 'numpy.ndarray'>
1


In [ ]:
y=[1,2,3,4]
print(y,type(y))


[1, 2, 3, 4] <class 'list'>


In [ ]:
%timeit [j**4 for j in range(1,9)]      #list time

8.69 µs ± 4.27 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%timeit np.arange(1,9)**4              # numpy array time is less than list

3.72 µs ± 1.25 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


**ARRAY CREATION**

In [ ]:
l=[]                  #1D array
for i in range(1,5):
  int_1=int(input("enter:"))
  l.append(int_1)

print(np.array(l))

enter:5
enter:6
enter:5
enter:5
[5 6 5 5]


In [ ]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])         #2D array
print(ar2)
print(ar2.ndim)

a2 = np.array([[1,2,3,4]])                   #2D array
print(a2)
print(a2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2
[[1 2 3 4]]
2


In [ ]:
ar3 = np.array([[[1,2,3,4],[1,2,3,4]]])        #3D array
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]]]
3


In [ ]:
arn = np.array([1,2,3,4],ndmin = 10)           #nD array
print(arn)                                     #ndmin set no of dim
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


**SPECIAL ARRAY CREATION**

In [ ]:
#zeros
arr = np.zeros(4)          #1D
arr_1 = np.zeros((3,4))     #2D

print(arr)
print()
print(arr_1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#ones
arr = np.ones(4)
print(arr)

[1. 1. 1. 1.]


In [ ]:
#empty array
arr = np.empty(4)
print(arr)

[1. 1. 1. 1.]


In [ ]:
#range
arr= np.arange(4)
print(arr)

[0 1 2 3]


In [ ]:
#identity matrix
arr = np.eye(3)      # 3X3
print(arr)
print()
arr1 = np.eye(3,5)    # 3X5
print(arr1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
#linspace
arr = np.linspace(0,20,num=5)
print(arr)

[ 0.  5. 10. 15. 20.]


**CREATING RANDOM VALUE ARRAY**

In [ ]:
#rand()         (GENERATE NO B/W 0,1)
var=np.random.rand(4)    #1D
print(var)
print()
var1=np.random.rand(3,5)    #2D
print(var1)

[0.51984507 0.72476066 0.00383315 0.83341202]

[[0.15054428 0.82440757 0.32013484 0.55505681 0.4131484 ]
 [0.17760457 0.32303256 0.88523015 0.16331374 0.570822  ]
 [0.80622935 0.16047366 0.67328118 0.59777068 0.76872426]]


In [ ]:
#randn()               value close to 0 (+ve,-ve)
var1 =np.random.randn(4)
print(var1)

[-0.09050216  2.22756315  0.697822    1.8774782 ]


In [ ]:
#ranf()               range [0.0,1.0)
var=np.random.ranf(4)
print(var)

[0.69143451 0.73259693 0.66836684 0.04210575]


In [ ]:
#randint(min,max,total_no)            generate random no b/w given range
var=np.random.randint(5,18,4)
print(var)

[ 9  7 16  8]


**DATA TYPE**

In [ ]:
var=np.array([1,2,3,4])
print(type(var))
print("data type:",var.dtype)

<class 'numpy.ndarray'>
data type: int64


**Conversion to other data type**

In [ ]:
x=np.array([1,2,3,4],dtype=np.int8)
print(x)


[1 2 3 4]


In [ ]:
x=np.array([1,2,3,4],dtype="f")

In [ ]:
x=np.array([1,2,3,4])
new=np.float32(x)
print(new)

[1. 2. 3. 4.]


**ARITHMETIC OP**

In [ ]:
x=np.array([1,2,3,4])
addn=x+3    #similarly other arithmetic op
print(add)

[4 5 6 7]


In [ ]:
x=np.array([1,2,3,4])
y=np.array([2,3,4,5])
addn=x+y              #addn=np.add(x,y)
print(add)

[3 5 7 9]


In [ ]:
x=np.array([1,2,3,4])
rec=np.reciprocal(x)
print(rec)

[1 0 0 0]


In [ ]:
#2d array
x=np.array([[1,2,3,4],[1,2,3,4]])
y=np.array([[2,3,4,5],[1,2,3,4]])
addn=x+y              #addn=np.add(x,y)
print(addn)



[[3 5 7 9]
 [2 4 6 8]]


**ARITHMETIC FUNCTIONS**

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(np.max(a), np.argmax(a))

6 5


In [ ]:
#2D
a=np.array([[1,2,3,4],[3,5,5,6]])
print(np.max(a,axis=1))

[4 6]


In [ ]:
print(np.max(a,axis=0))

[3 5 5 6]


In [ ]:
a=np.array([1,2,3,4,5,8])
print(np.cumsum(a))

[ 1  3  6 10 15 23]


**SHAPE & RESHAPING**

In [ ]:
import numpy as np
a=np.array([[1,3,4,5,6],[3,5,6,6,7]])
print(a.shape)


(2, 5)


In [ ]:
a=np.array([1,2,4,5,6,7],ndmin=10)
print(a)
print()
print(a.ndim)
print()
print(a.shape)

[[[[[[[[[[1 2 4 5 6 7]]]]]]]]]]

10

(1, 1, 1, 1, 1, 1, 1, 1, 1, 6)


In [ ]:
#reshaping......converting 1D to 2D
a=np.array([1,2,3,4,5,6])
print(a.ndim)
print()
y=a.reshape(2,3)
print(y)
print(y.ndim)

1

[[1 2 3]
 [4 5 6]]
2


In [ ]:
a=np.array([1,2,3,4,5,6])
print(a.ndim)
print()
y=a.reshape(3,3)
print(y)
print(y.ndim)

1



ValueError: cannot reshape array of size 6 into shape (3,3)

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
print(a.ndim)
print()
x=a.reshape(3,3)
print(x)
print(x.ndim)

[1 2 3 4 5 6 7 8 9]
1

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
print(a.ndim)
print()
x=a.reshape(2,3,2)           #2 row,   3 inner rows, 2 cols.....converted to 3D
print(x)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [ ]:
#converting nD to 1D array
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
print(a.ndim)
print()
x=a.reshape(2,3,2)           #2 row,   3 inner rows, 2 cols
print(x)
print(x.ndim)

new=x.reshape(-1)      #1D conversion
print(new)
print(new.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


**BROADCASTING**

In [ ]:
a=np.array([1,2,3,4])           #broadcasting error
b=np.array([1,2,3])
print(a+b)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
import numpy as np
x=np.array([[1,2,3],[2,4,6]])      # 2X3
y=np.array([[1],[2]])              # 2X1
print(x+y)                         #max = 2X3

[[2 3 4]
 [4 6 8]]


**INDEXING**

In [ ]:
#1D array
x=np.array([1,2,3,4])
print(x[2])
print(x[-1])


3
4


In [ ]:
#2D array
x=np.array([[1,2,34,4],[3,4,5,7]])
print(x.ndim)
print(x[0,2])

2
34


In [ ]:
#3D array
x=np.array([[[1,2,3],
             [3,4,5]],
            [[3,5,6],
            [4,5,7]]])
print(x[0,1,1])

4


In [ ]:
x=np.array([[[1,2],[3,4]]])
print(x)
print()
print(x.ndim)
print(x[0,1,0])

[[[1 2]
  [3 4]]]

3
3


**SLICING**

In [ ]:
#1D aray
x=np.array([1,2,3,4,5,6])
print(x[2:])

[3 4 5 6]


In [ ]:
#2D array
x=np.array([[1,2,3,4],[3,5,6,7]])
print(x[0,1:3])

[2 3]


In [ ]:
#3D array
x=np.array([[[1,2],[3,4]]])
print(x[0,1,:])

[3 4]


**ITERATION**

In [ ]:
#1D array
x=np.array([1,3,4,56,77,44])
for i in x:
  print(i)

1
3
4
56
77
44


In [ ]:
#2D
x=np.array([[1,2,3,4],[3,4,5,6]])
print(x)
print()
for i in x:
  print(i)

for i in x:
  for j in i:
    print(j)

[[1 2 3 4]
 [3 4 5 6]]

[1 2 3 4]
[3 4 5 6]
1
2
3
4
3
4
5
6


In [ ]:
#3D
x=np.array([[[1,2,3],[3,3,4]]])
for i in x:
  for j in i:
    for k in j:
      print(k)

1
2
3
3
3
4


In [ ]:
#3D array iterating using nditer fun
x=np.array([[[1,2,3],[3,3,4]]])
for i in np.nditer(x):
  print(i)

1
2
3
3
3
4


In [ ]:
x=np.array([[[1,2,3],[3,3,4]]])
for i in np.nditer(x,flags=['buffered'],op_dtypes=["S"]):     #change dtype
  print(i)

b'1'
b'2'
b'3'
b'3'
b'3'
b'4'


In [ ]:
x=np.array([[[1,2,3],[3,3,4]]])
for i,d in np.ndenumerate(x):             #indexing+ iterartion
  print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 3
(0, 1, 1) 3
(0, 1, 2) 4


**COPY vs VIEW**

In [ ]:
x=np.array([1,1,2,4])
y=x.copy()    #copy
x[1]=7
print(x)
print(y)

[1 7 2 4]
[1 1 2 4]


In [ ]:
x=np.array([1,1,2,4])
y=x.view()    #view
x[1]=8
print(x)
print(y)

[1 8 2 4]
[1 8 2 4]


**JOIN**

In [ ]:
#1D array
x=np.array([1,2,3,4])
y=np.array([6,7,8,9])
z=np.concatenate((x,y))
print(z)

[1 2 3 4 6 7 8 9]


In [ ]:
#2D array
x=np.array([[1,1,2,4,5,6],[3,5,7,7,8,9]])
y=np.array([[14,6,8,9,9,6],[3,54,5,4,5,9]])
print(x)
print()
print(y)
print()
z=np.concatenate((x,y),axis=0)
a=np.concatenate((x,y),axis=1)
print(z)
print()
print(a)


[[1 1 2 4 5 6]
 [3 5 7 7 8 9]]

[[14  6  8  9  9  6]
 [ 3 54  5  4  5  9]]

[[ 1  1  2  4  5  6]
 [ 3  5  7  7  8  9]
 [14  6  8  9  9  6]
 [ 3 54  5  4  5  9]]

[[ 1  1  2  4  5  6 14  6  8  9  9  6]
 [ 3  5  7  7  8  9  3 54  5  4  5  9]]


In [ ]:
x=np.array([1,2,3,4,5])
y=np.array([9,8,7,6,5])
new=np.stack((x,y),axis=1)
print(new)

[[1 9]
 [2 8]
 [3 7]
 [4 6]
 [5 5]]


In [ ]:
x=np.array([1,2,3,4,5])
y=np.array([9,8,7,6,5])
new=np.stack((x,y),axis=0)
print(new)

[[1 2 3 4 5]
 [9 8 7 6 5]]


In [ ]:
x=np.array([1,2,3,4,5])
y=np.array([9,8,7,6,5])
new=np.hstack((x,y))
print(new)

[1 2 3 4 5 9 8 7 6 5]


In [ ]:
x=np.array([1,2,3,4,5])
y=np.array([9,8,7,6,5])
new=np.vstack((x,y))
print(new)

[[1 2 3 4 5]
 [9 8 7 6 5]]


In [ ]:
x=np.array([1,2,3,4,5])
y=np.array([9,8,7,6,5])
new=np.dstack((x,y))     #along height
print(new)

[[[1 9]
  [2 8]
  [3 7]
  [4 6]
  [5 5]]]


**SPLITTING**

In [ ]:
#1D array
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)
print()
new=np.array_split(a,3)
print(new)
print(type(new))

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>


In [ ]:
#2D array
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print()
new=np.array_split(a,3)
print(new)
print(type(new))

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
<class 'list'>


In [ ]:
#2D array
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print()
new=np.array_split(a,3,axis=1)
print(new)
print(type(new))

[[1 2]
 [3 4]
 [5 6]]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]
<class 'list'>


**NUMPY ARRAYS FUNCTIONS**
(search,sort,search sorted,filter)

**SEARCH**

In [ ]:
a=np.array([1,2,3,4,5,4,2,3,2,32,2])
x=np.where(a==2)                          #return index where 2 is present
print(x)

(array([ 1,  6,  8, 10]),)


In [ ]:
a=np.array([1,2,4,6,22,3,5,65,7,8,9])
x=np.where((a%2)==0)
print(x)

(array([1, 2, 3, 4, 9]),)


**SEARCH SORTED ARRAY**

In [ ]:
#left to right
a=np.array([1,2,3,4,6,7])
# index     0,1,2,3,4,5
x=np.searchsorted(a,5)
print(x)

4


In [ ]:
#right to left
a=np.array([1,2,3,4,6])
# index     0,1,2,3,4
x=np.searchsorted(a,5,side="right")
print(x)

4


In [ ]:
a=np.array([1,2,3,4,7])
# index     0,1,2,3,4
x=np.searchsorted(a,[5,6])
print(x)

[4 4]


**SORT**

In [ ]:
a=np.array([7,4,5,2,8,4,6,1])
x=np.sort(a)
print(x)

[1 2 4 4 5 6 7 8]


In [ ]:
a=np.array(['a','h','b'])
print(np.sort(a))

['a' 'b' 'h']


In [ ]:
#2D array
x=np.array([[1,4,2],[6,4,7],[9,3,12]])
print(x)
print(np.sort(x))

[[ 1  4  2]
 [ 6  4  7]
 [ 9  3 12]]
[[ 1  2  4]
 [ 4  6  7]
 [ 3  9 12]]


In [ ]:
#2D array
x=np.array([[1,4,2],[6,4,7],[9,3,12]])
print(x)
print(np.sort(x,axis=0))

[[ 1  4  2]
 [ 6  4  7]
 [ 9  3 12]]
[[ 1  3  2]
 [ 6  4  7]
 [ 9  4 12]]


**FILTER ARRAY**

In [ ]:
a=np.array(["a","r","p","i","t"])
f=[True,False,True,False,False]
new=a[f]
print(new)
print(type(new))

['a' 'p']
<class 'numpy.ndarray'>


**ARITHMETIC FUNCTIONS**
**(shuffle,unique,resize,flatten,ravel)**

shuffle

In [ ]:
#shuffle
x=np.array([1,2,5,3,2])
np.random.shuffle(x)
print(x)

[2 1 2 5 3]


unique

In [ ]:
#unique.....remove duplicacy
x=np.array([2,4,2,5,3,7,4,7,3,2])
a=np.unique(x)
print(a)

[2 3 4 5 7]


In [ ]:
x=np.array([2,4,2,5,3,7,4,7,3,2])
a=np.unique(x,return_index=True)
print(a)

(array([2, 3, 4, 5, 7]), array([0, 4, 1, 3, 5]))


In [ ]:
x=np.array([2,4,2,5,3,7,4,7,3,2])
a=np.unique(x,return_index=True,return_counts=True)
print(a)

(array([2, 3, 4, 5, 7]), array([0, 4, 1, 3, 5]), array([3, 2, 2, 1, 2]))


**reshape**:Does not alter the original data.....
Requires that the number of elements remains constant......
Returns a new array.**(copy)**

**resize**:Can alter the original data (in-place if used as a method).....
Allows the total number of elements to change......
If the new size is larger, fills with repeated data; if smaller, truncates data**.(view)**

resize

In [ ]:
#resize...change size of an array
x=np.array([1,2,3,4,5,6])
a=np.resize(x,(2,3))
print(a)

[[1 2 3]
 [4 5 6]]


**Differencesb/w flatten & ravel:**

**Memory Allocation:**
flatten: returns a new array, thus always allocates new memory.
ravel: Returns a view of the original array if possible, otherwise, returns a copy.

**Return Type:**
flatten: Always returns a new copy of the array.
ravel: Returns a view if possible; otherwise, returns a copy.

**Use Case:**
Use flatten when you need a new, independent one-dimensional array.
Use ravel when you prefer a view for efficiency, but are okay with a copy if necessary.

FLATTEN

In [ ]:
#flatten.....convert to 1D array
x=np.array([1,2,3,4,5,6])
a=np.resize(x,(2,3))
print(a)
print()
b=a.flatten()           #row wise(by default ="C")
print(b)


[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


In [ ]:
x=np.array([1,2,3,4,5,6])
a=np.resize(x,(2,3))
print(a)
print()
b=a.flatten(order="F")      #col wise
print(b)

[[1 2 3]
 [4 5 6]]

[1 4 2 5 3 6]


Ravel

In [ ]:
#ravel also convert array to 1D
x=np.array([1,2,3,4,5,6])
a=np.resize(x,(2,3))
print(a)
print()
b=np.ravel(a,order="F")      #col wise
print(b)

[[1 2 3]
 [4 5 6]]

[1 4 2 5 3 6]


**insert**

In [ ]:
a=np.array([1,2,3,4,5])
x=np.insert(a,1,69)       # arr,pos,no
print(x)

[ 1 69  2  3  4  5]


In [ ]:
a=np.array([1,2,3,4,5])
x=np.insert(a,(1,3),69)       # arr,pos,no
print(x)

[ 1 69  2  3 69  4  5]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
x=np.insert(a,(1,3),4.5)       # convert float to int
print(x)

[1 4 2 3 4 4 5]


In [ ]:
#2D array
a=np.array([[1,2,3],[4,5,6]])
x=np.insert(a,2,17,axis=0)       #arr,pos,no,axis
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [17 17 17]]


In [ ]:
#2D array
a=np.array([[1,2,3],[4,5,6]])
x=np.insert(a,2,17,axis=1)       #arr,pos,no,axis
print(x)

[[ 1  2 17  3]
 [ 4  5 17  6]]


In [ ]:
#2D array
a=np.array([[1,2,3],[4,5,6]])
x=np.insert(a,2,17)       #arr,pos,no
print(x)

[ 1  2 17  3  4  5  6]


In [ ]:
#2D array
a=np.array([[1,2,3],[4,5,6]])
x=np.insert(a,2,[22,23,24],axis=0)       #arr,pos,no,axis
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [22 23 24]]


In [ ]:
#2D array
a=np.array([[1,2,3],[4,5,6]])
x=np.insert(a,2,[22,23],axis=1)       #arr,pos,no,axis
print(x)

[[ 1  2 22  3]
 [ 4  5 23  6]]


In [ ]:
#2D array
a=np.array([[1,2,3],[4,5,6]])
x=np.insert(a,2,[17,18])       #arr,pos,no,axis
print(x)

[ 1  2 17 18  3  4  5  6]


append

In [ ]:
x=np.array([1,2,3,4,5])
y=np.append(x,4)              #arr,no
print(y)

[1 2 3 4 5 4]


In [ ]:
#2d array
x=np.array([[1,2,3],[4,5,6]])
y=np.append(x,[[6,7,8]],axis=0)
print(y)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [ ]:
#2d array
x=np.array([[1,2,3],[4,5,6]])
y=np.append(x,[[6],[8]],axis=1)
print(y)

[[1 2 3 6]
 [4 5 6 8]]


delete

In [ ]:
x=np.array([4,2,25,3,34,4])
y=np.delete(x,4)           #arr,index
print(y)

[ 4  2 25  3  4]


**MATRIX IN NUMPY**

In [ ]:
#creating numpy matrix
x=np.matrix([[1,2,3],[4,5,6]])
print(x)
print(type(x))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [ ]:
#creating numpy array
x=np.array([[1,2,3],[4,5,6]])
print(x)
print(type(x))


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


arithmetic o/p on matrix

In [ ]:
a=np.matrix([[1,2],[3,5]])
b=np.matrix(np.ones((2,2)))
print("a=",a)
print()
print("b=",b)
print()
print(a+b)               #add
print()
print(a*b)               #mul
print()
print(a.dot(b))          #mul

a= [[1 2]
 [3 5]]

b= [[1. 1.]
 [1. 1.]]

[[2. 3.]
 [4. 6.]]

[[3. 3.]
 [8. 8.]]

[[3. 3.]
 [8. 8.]]


In [ ]:
#arithmetic o/p on array
a=np.array([[1,2],[3,5]])
b=np.array(np.ones((2,2)))
print("a=",a)
print()
print("b=",b)
print()
print(a+b)               #add
print()
print(a*b)               #mul



a= [[1 2]
 [3 5]]

b= [[1. 1.]
 [1. 1.]]

[[2. 3.]
 [4. 6.]]

[[1. 2.]
 [3. 5.]]


**# matrix fun in numpy**

transpose

In [ ]:
x=np.matrix([[1,2,3],[4,56,8]])
print(x)
print()
y=np.transpose(x)     #transpose
print(y)
print()
z=x.T                 #transpose
print(z)

[[ 1  2  3]
 [ 4 56  8]]

[[ 1  4]
 [ 2 56]
 [ 3  8]]

[[ 1  4]
 [ 2 56]
 [ 3  8]]


**swapaxes**

In [ ]:
#swapaxes........convert row to col & vice versa
x=np.matrix([[1,2,3],[4,5,6]])
print(x)
print()
y=np.swapaxes(x,0,1)
print(y)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


inverse

In [ ]:
x=np.matrix([[1,2],[4,5]])
print(x)
print()
y=np.linalg.inv(x)        #inverse
print(y)


[[1 2]
 [4 5]]

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


power

In [ ]:
x=np.matrix([[1,2],[4,5]])
print(x)
print()
y=np.linalg.matrix_power(x,2)        #arr,n.....here n>0.....so pwr(mul)
print(y)

[[1 2]
 [4 5]]

[[ 9 12]
 [24 33]]


In [ ]:
x=np.matrix([[1,2],[4,5]])
print(x)
print()
y=np.linalg.matrix_power(x,0)        #arr,n.....here n=0.....so identity matrix
print(y)

[[1 2]
 [4 5]]

[[1 0]
 [0 1]]


In [ ]:
x=np.matrix([[1,2],[4,5]])
print(x)
print()
y=np.linalg.matrix_power(x,-2)        #arr,n.....here n<0.....so inverse
print(y)

[[1 2]
 [4 5]]

[[ 3.66666667 -1.33333333]
 [-2.66666667  1.        ]]


determinant

In [ ]:
x=np.matrix([[1,2],[3,4]])
print(x)
print()
y=np.linalg.det(x)
print(y)

[[1 2]
 [3 4]]

-2.0000000000000004


**classwork(training)**

In [ ]:
import numpy as np
a=np.array([1,2,3,4])
a[2]=10.6      #truncate float value & convert it to int
print(a)

[ 1  2 10  4]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a[1,3]=-1
print(a)
print()
a[1]

[[ 1  2  3  4]
 [ 5  6  7 -1]]



array([ 5,  6,  7, -1])

**STRIDES**(how many bytes skip to go to the next row /col)

results in tuple(row,col)

arr.strides[0]  bytes to skip to move to the next row.

arr.strides[1] bytes to skip to move to the next col.
(**int-4byte.....,float-8byte.......bool-1byte)**

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8]],dtype=np.int32)
print(a)
print()
print(a.strides)
print()
print(a.T .strides)

[[1 2 3 4]
 [5 6 7 8]]

(16, 4)

(4, 16)


In [ ]:
#slicing is a view not copy
a=np.array([[1,2,3,4],[5,6,7,8]])
a[0,::2]=10
print(a)

[[10  2 10  4]
 [ 5  6  7  8]]


In [ ]:
a=np.array([1,2,3,4])
b=a[0:3]
print(b)
print()
print(a)

[1 2 3]

[1 2 3 4]


In [ ]:
a=np.arange(36).reshape(6,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


**Fancy /advanced indexing**
pass arrays of indices in place of single scalars

 fancy indexing creates copies instead of views

In [ ]:
#indexing by position
a=np.arange(0,80,10)
print(a)
x=a[[0,3,5]]
print(x)
y=np.take(a,[0,3,5])    #using take
print(y)

[ 0 10 20 30 40 50 60 70]
[ 0 30 50]
[ 0 30 50]


In [ ]:
#using T/F
a=np.array([0,10,20,30,40,50,60])
mask=np.array([0,0,1,1,0,1,1],dtype=bool)
y=a[mask]
print(y)

[20 30 50 60]


In [ ]:
 #using compress fun
y = np.compress(mask, a)
print(y)

[20 30 50 60]


In [ ]:
#in multiple dimensions
a=np.array([[1,2,3,4],[6,7,8,9]])
row=np.array([0,1])
col=np.array([2,0])
a[row,col]


array([3, 6])

In [ ]:
#simple indexing in 1D
x=np.array([1,2,3,4,5,6])
x[[2,4]]

array([3, 5])

In [ ]:
x=np.array([1,3,4,5,6,6723,75,45])
a=np.array([0,4,5])
x[a]

array([   1,    6, 6723])

combining fancy indexing with other scheme

In [ ]:
#combine fancy and simple indices:
a=np.arange(18).reshape(2,3,3)
print(a)
a[0,1,[2,1]]


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


array([5, 4])

In [ ]:
#combine fancy indexing with slicing
x=np.array([[1,2,3],[4,5,6]])
x[:,[2,0]]

array([[3, 1],
       [6, 4]])

In [ ]:
#Modifying Values with Fancy Indexing
x=np.array([1,2,3,4,5])
a=np.array([0,3,2])
x[a]=69
print(x)

[69  2 69 69  5]


In [ ]:
#accessing one to one mapping, 0,1    1,2   2,3
arr=np.array([[0,1,2,3],
[10,11,12,13],
[20,21,22,23]])
arr[(0,1,2),(1,2,3)]   #list of tuples

array([ 1, 12, 23])

In [ ]:
arr[1:,[0,2]]

array([[10, 12],
       [20, 22]])

In [ ]:
a=np.arange(12).reshape(3,4)
print(a)
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))
print(np.sum(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]
66


In [ ]:
a=np.array([1,2,3,4])
np.amin(a)

1

** Filtering numpy array**

In [ ]:
x=np.array([1,2,3,5])
mask=x>2
print(mask)
print(x[mask])    #x[x>2]

[False False  True  True]
[3 5]


**CLIP ........ Given an interval, values outside the interval are clipped to the interval edges.**

In [ ]:
import numpy as np
x=np.array([1,2,3,4,7,8,6,4])
x.clip(2,4)         #val ranges b/w 2 and 4

array([2, 2, 3, 4, 4, 4, 4, 4])

In [ ]:
x=np.array([1,2,3,4,7,8,6,4])
x.clip(2,4,out=x)   #out=x makes this op in-place, modify original arr directly.

array([2, 2, 3, 4, 4, 4, 4, 4])

**PTP(peek to peek)**
gives (max-min)

In [ ]:
x=np.arange(12).reshape(3,4)
print(x)
print()
x.ptp(axis=0)    #x.ptp(0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



array([8, 8, 8, 8])

In [ ]:
x=np.arange(12).reshape(3,4)
print(x)
print()
x.ptp(axis=1)      #x.ptp(1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



array([3, 3, 3])

In [ ]:
x=np.arange(12).reshape(3,4)
print(x)
print()
x.ptp()      #axis=None

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



11

In [ ]:
#concatenation
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

concat1 = np.concatenate((arr1, arr2), axis=0)
concat2 = np.concatenate((arr1, arr2.T), axis=1)

print(concat1)
print(concat2)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
